### PR TITLE
Mention look-up-cli

### PR DESCRIPTION
**Pull request by lydell**
I found this module useful as a CLI tool, so I made one. Perhaps others find it useful too.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
awesome! thanks! Looking forward to reviewing this tomorrow!

**Comment by lydell** [comment]
I just saw that Travis failed, but as far as I can tell it has nothing to do with the tiny readme change of this PR.

Merge or close :) ? (Or adjust?)

**Comment by jonschlinkert** [comment]
no, it's totally fine. I'll get it fixed and merge your pr in. just trying to wrap something up first. thanks for checking into it.

**Comment by lydell** [comment]
I’ve amended the commit, updating .verb.md instead. I tried installing verb and verb-cli and then running `verb`, which indeed did update README.md, but it made _lots_ of changes, so I’m leaving that out, since I’m not sure I did things right or if it really belongs to this PR.

**Comment by jonschlinkert** [comment]
thanks!

**Comment by jonschlinkert** [comment]
I did a patch bump and published to npm so the docs would be seen on npm too. thanks again!

**Pull request merged**
