### PR TITLE
Adds test for globbing forked trees.

### PR DESCRIPTION
**Pull request by shannonmoeller**
Adds a failing test case for the issue discovered in #3.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
@shannonmoeller I don't think those tests actually should pass. the pattern doesn't match the file path. 

I think that should only pass if the `expected` path were changed to `'fixtures/a/b/c/d/e/f/g/c/k/l/package.json'`

**Comment by shannonmoeller** [comment]
I'm probably misunderstanding the purpose of `**/`. Should I drop it?

**Comment by doowb** [comment]
@shannonmoeller I think what you're asking for could cause a lot of problems if `look-up` searched down other branches. The easiest one to see is if you're in a module that's in `node_modules` and you're searching for some configuration file like `.jshintrc`. If one doesn't exist in your own module, then it would search in a sibling module and that's not something you'd want.

I think you're example of doing `['.waldo', '.config/waldo']` is the right way to go since `look-up` sees those as normal file paths. I think you can dynamically generate `waldo` piece in `find-config`.

@jonschlinkert might have different thoughts on this and I might be completely wrong :wink:

**Comment by jonschlinkert** [comment]
> I'm probably misunderstanding the purpose of **/. Should I drop it?

well, it's not you... depending on what lib you're using, a different recursion strategy will be used. so it's definitely confusing. I've been using globs for a while and some of this really didn't click with me until I tried creating libs for it with unit tests... 

@doowb's point is that this would basically work like node-glob and "recurse down" into directories. 

In other words, given the path `a/b/c/d`, this libraries recursively removes a segment when it can't find your pattern, until we get to `a` and then finally `/`. But file searching in general - like you would do with node-glob - works the other way, recursing "down" into sub-directories. So `a/b/c/d` gets longer, until there are no more child directories to search.

actually, that reminds me of the reason for the pr and why I created this. Since node-glob is used in findup-sync, every time findup-sync lops off a path segment to go "up", node-glob will try to recurse down again, obviously extremely inefficient, and it's not surprising or magical why this is 150x faster - and in some cases, more accurate. For example, when I was doing unit tests, there were times when I tried to find a non-existent package.json in the root of a project,  and node-glob recursed down into test fixtures and found a package.json fixture. But we don't want it to recurse down, only up.

anyway hope this helps.

**Comment by jonschlinkert** [comment]
fwiw, I was thinking about your use case, and maybe it's worth considering not using globbing at all. I think it would be valuable if the lib just resolved the `.config` directory paths, allowing implementors to use their own matching tool. 

for a different use case, I tried to do something like that here: https://github.com/jonschlinkert/resolve-up/blob/master/index.js#L57-L105

**Comment by shannonmoeller** [comment]
@doowb I thought that might cause performance issues. Just caught off guard when I was expecting feature parity with findup-sync. Bad assumption.

@jonschlinkert Agreed, which is why I dropped globbing altogether when throwing together [find-config](https://www.npmjs.com/package/find-config). Is it worthwhile keeping the fixtures and inverting the test case to expect null?

**Comment by jonschlinkert** [comment]
> just caught off guard when I was expecting feature parity with findup-sync.

that pattern does work with findup-sync currently? hmm, it seems like it shouldn't. this needs to have parity if that's correct. 

> Is it worthwhile keeping the fixtures and inverting the test case to expect null?

for globbing you mean?

**Comment by shannonmoeller** [comment]
> that pattern does work with findup-sync

Yes.

image

>> inverting the test case

> for globbing you mean?

That's what I meant, yes. But, because `.{,config/}waldo` is working for findup-sync, this may still be an issue.

**Comment by shannonmoeller** [comment]
Looks like there's little chance of this getting merged. Especially now that it has conflicts. Closing.

**Pull request closed without merging**
